app:
  addr: 127.0.0.1:3000
  setmode: debug
mysql:
  host: 127.0.0.1
  port: 3306
  username: xxxxx
  password: xxx
  database: xxxx
  parsetime: false
  debug: true
ReverseProxy:
  Scheme: http
  Host: 127.0.0.1:8000